companieshouse/auth-code-notification

- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .gitignore
https://companieshouse.atlassian.net/browse/ROE-2107
Adding pull request template, dependabot config and gitignore file
> ROE-2107 add dependabot and pull request template

- pom.xml
https://companieshouse.atlassian.net/browse/ROE-2131
Add sonar config to maven pom
```
```
- types other than `fix:` and `feat:` are allowed, for example …
> ROE-2131 Add sonar config to pom

- pom.xml
https://companieshouse.atlassian.net/browse/ROE-2109
Added structured logger to maven pom
```
```
- types other than `fix:` and `feat:` are allowed, for …
> ROE-2109 Add structured logger

- pom.xml
Part of [ROE-2101](https://companieshouse.atlassian.net/browse/ROE-2101) and resolves [ROE-2105](https://companieshouse.atlassian.net/browse/ROE-2105)
Add `jib-maven-plugin` plugin to dockerize auth-code-notification service
[ROE-2101]: https://companieshouse.atlassian.net/browse/ROE-2101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ROE-2105]: https://companieshouse.atlassian.net/browse/ROE-2105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add jib-maven-plugin plugin to dockerize auth-code-notification service

- spec/schema.json
https://companieshouse.atlassian.net/browse/ROE-2112
Swagger spec base.
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, …
> ROE-2112 Swagger spec base

- README.md
https://companieshouse.atlassian.net/browse/ROE-2106
Updating the Readme file for the auth-code-notification service
```
``` …
> ROE-2108 Updating readme

- spec/schema.json
https://companieshouse.atlassian.net/browse/ROE-2197
Adding the initial version of the Swagger spec file schema.json for the POST endpoint for send-email
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any …
> ROE-2197 TL Add initial swagger spec schema.json

- Tiltfile.dev
https://companieshouse.atlassian.net/browse/ROE-2101
Adding tiltfile required by docker 
```
```
- types other than `fix:` and `feat:` are allowed, for …
> ROE-2101 Add tiltfile so this can run on docker

- start.sh
https://companieshouse.atlassian.net/browse/ROE-2203
Added java exec line to start.sh script.
```
```
- types other than `fix:` and `feat:` are allowed, for …
> ROE-2203 TL Add java exec line to start script

- pom.xml
- src/main/java/uk/gov/companieshouse/authcodenotification/client/ApiClientService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/exception/ServiceException.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalService.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/utils/ApiLoggerTest.java
https://companieshouse.atlassian.net/browse/ROE-2196
Added required service code to call the sdk and retrieve the email for the specified company from the oracle query api.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part …
> Roe 2196 add authcodeservice

- pom.xml
- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/utils/Constants.java
- src/main/java/uk/gov/companieshouse/authcodenotification/utils/DataSanitisation.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/utils/DataSanitisationTest.java
https://companieshouse.atlassian.net/browse/ROE-2200
Added OWASP based data encoder to sanitise input data sent to the new endpoint.
```
```
- types other …
> Roe 2200 sanitise data input for logging

- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/model/SendEmailRequestDto.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-2213
Add and integrate dto model for the request body containing the auth code.
```
```
- types other than …
> ROE-2213 Add dto model for request body posted

- pom.xml
- src/main/java/uk/gov/companieshouse/authcodenotification/config/ApplicationConfiguration.java
- src/main/java/uk/gov/companieshouse/authcodenotification/config/KafkaConfiguration.java
- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/email/AvroSerializer.java
- src/main/java/uk/gov/companieshouse/authcodenotification/email/EmailContent.java
- src/main/java/uk/gov/companieshouse/authcodenotification/email/KafkaEmailClient.java
- src/main/java/uk/gov/companieshouse/authcodenotification/email/KafkaRestClient.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/EmailService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/utils/FormatUtils.java
- src/test/java/uk/gov/companieshouse/authcodenotification/TestUtils.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/email/AvroSerializerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/email/EmailContentTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/email/KafkaEmailClientTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/email/KafkaRestClientTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/EmailServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/utils/FormatUtilsTest.java
- src/test/resources/email/email-send.avsc
https://companieshouse.atlassian.net/browse/ROE-2199
Adding kafka configuration and email service to send kafka message to chs-email-sender
```
```
- types …
> ROE-2199 use kafka to send email

- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/EmailService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalService.java
https://companieshouse.atlassian.net/browse/ROE-2173
Updating/improving the messages logged for a successful email send
```
``` …
> ROE-2173 Updating logging messages

- src/main/java/uk/gov/companieshouse/authcodenotification/client/ApiClientService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/PublicDataRetrievalService.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/PublicDataRetrievalServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-2216
Using the internal api, obtain company name and add to the email data.
```
```
- types other than `fix:` …
> Roe 2216 obtain company name add to email

- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/utils/DataSanitisation.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/utils/DataSanitisationTest.java
https://companieshouse.atlassian.net/browse/ROE-2217
Reused owasp encoder to sanitise the auth code in the request body.
```
```
- types other than `fix:` …
> ROE-2217 Sanitise auth code string

- README.md
https://companieshouse.atlassian.net/browse/ROE-2208
Updated the readme
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, …
> ROE-2208 auth code endpoint information

- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/PublicDataRetrievalService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/utils/DataSanitiser.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/PublicDataRetrievalServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/utils/DataSanitiserTest.java
https://companieshouse.atlassian.net/browse/ROE-2173
* Renamed references of email to emailAddress
* Made log messages consistent
* Renamed DataSanitisation to DataSanitiser
* Updated private/public data retrieval tests to check the correct value was used in the url and that the value returned from our methods is correct.
```
```
- BREAKING CHANGE: a …
> ROE-2173 Cleanup logging, improve tests and naming

- pom.xml
- spec/schema.json
- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/model/SendEmailRequestDto.java
- src/main/java/uk/gov/companieshouse/authcodenotification/validation/AuthCodeEmailValidator.java
- src/main/java/uk/gov/companieshouse/authcodenotification/validation/utils/ValidationUtils.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/utils/DataSanitiserTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/validation/AuthCodeEmailValidatorTest.java
https://companieshouse.atlassian.net/browse/ROE-2221
Added validation similar to that in the overseas entities api.
```
``` …
> Roe 2221 validate specific format

- routes.yaml
- spec/schema.json
- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
https://companieshouse.atlassian.net/browse/ROE-2232
Internal prefix on endpoint.
```
```
- types other than `fix:` and `feat:` are allowed, for example …
> ROE-2232 Endpoint requires internal prefix

- spec/schema.json
https://companieshouse.atlassian.net/browse/ROE-2221
Update swagger spec server url to use internalapi
```
```
- types other than `fix:` and `feat:` are …
> ROE-2221 Update swagger sepc to reflect internalapi domain

- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/exception/EncryptionException.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/utils/Encrypter.java
- src/main/java/uk/gov/companieshouse/authcodenotification/validation/AuthCodeEmailValidator.java
- src/main/java/uk/gov/companieshouse/authcodenotification/validation/utils/ValidationUtils.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/utils/EncrypterTest.java
https://companieshouse.atlassian.net/browse/ROE-2224
Encrypt the auth code before sending it via email
```
```
- types other than `fix:` and `feat:` are …
> ROE-2224 encrypt auth code before sending email

- src/main/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationController.java
- src/main/java/uk/gov/companieshouse/authcodenotification/exception/EntityNotFoundException.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalService.java
- src/main/java/uk/gov/companieshouse/authcodenotification/service/PublicDataRetrievalService.java
- src/test/java/uk/gov/companieshouse/authcodenotification/controller/AuthCodeNotificationControllerTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/PrivateDataRetrievalServiceTest.java
- src/test/java/uk/gov/companieshouse/authcodenotification/service/PublicDataRetrievalServiceTest.java
https://companieshouse.atlassian.net/browse/ROE-2262
Created a new exception class: EntityNotFoundException.
It extends ServiceException so it can be caught first in the controller.
Added this to both the public and private data retrieval service so made he name of the exception as generic as possible.
```
```
- BREAKING CHANGE: a commit that has a footer …
> ROE-2262 Company Not Found should be 404

- pom.xml
https://companieshouse.atlassian.net/browse/ROE-2256
* Call to retrieve company profile data should now auto-retry on failure and hopefully address the issue in the Staging environment
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE …
> ROE-2256 Bump version of the Java API SDK

- Makefile
- pom.xml
- suppress.xml
https://companieshouse.atlassian.net/browse/ROE-2260
* POM and Makefile changed so that dependency checker can be run from command-line and pipeline
* Empty suppression file added
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can …
> ROE-2260 Add dependency checker to build

- Makefile
- pom.xml
https://companieshouse.atlassian.net/browse/ROE-2276?atlOrigin=eyJpIjoiYTQxMzBhNjdmNGFhNGZjOGE4YWEzMDM1NTRiODM3MmUiLCJwIjoiaiJ9
Update spring boot dependencies and spring boot maven plugin to v 2.6.15
Json Library version update
Amend makefile so it doesn't block PR's temporarily until we resolve vulnerabilities (to allow us to merge fixes)
```
```
- …
> Roe 2276 fix spring version security issue

- src/main/java/uk/gov/companieshouse/authcodenotification/service/AuthCodeNotificationService.java
https://companieshouse.atlassian.net/browse/ROE-2269
AES key name changed
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, …
> ROE-2269 AES key reference renamed

- pom.xml
https://companieshouse.atlassian.net/browse/ROE-2276?atlOrigin=eyJpIjoiNGNhN2YwZDNhZWMxNDUzOWFiNjNhOGEzZTJkZjA1NzUiLCJwIjoiaiJ9
Updated spring libraries and json libraries to fix issues raised by dependency check. This fixes the follow issues:
- logback-core-1.2.7.jar: CVE-2021-42550(6.6)
- spring-web-5.3.13.jar: CVE-2021-22060(4.3), CVE-2022-22968(5.3), CVE-2023-20863(6.5), CVE-2023-20861(6.5), CVE-2023-20860(7.5), CVE-2022-22965(9.8), CVE-2022-22971(6.5), CVE-2022-22950(6.5), CVE-2022-22970(5.3)
- spring-boot-2.6.1.jar: CVE-2023-20883(7.5)
- spring-boot-starter-web-2.6.1.jar: CVE-2023-20883(7.5)
- spring-core-5.3.13.jar: CVE-2021-22060(4.3), CVE-2022-22968(5.3), CVE-2023-20863(6.5), CVE-2023-20861(6.5), CVE-2023-20860(7.5), CVE-2022-22965(9.8), CVE-2022-22971(6.5), CVE-2022-22950(6.5), …
> Roe 2276 fix dependency check issues

- pom.xml
https://companieshouse.atlassian.net/browse/ROE-2276?atlOrigin=eyJpIjoiOThiY2RjMGFkNDAxNDM4MGFjOGU5ZGNiNjY2ZDczYjUiLCJwIjoiaiJ9
Forcefully downgrade version of kafka-client in order to work with ch-kakfa.
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic …
> Roe 2276 fix kafka client compatibility with spring

- suppress.xml
https://companieshouse.atlassian.net/browse/ROE-2290
Suppress the following due to upgrades not currently being compatible with ch-kafka:
kafka-clients-3.0.0.jar: CVE-2022-34917(7.5), CVE-2023-25194(8.8)
snappy-java-1.1.8.1.jar: CVE-2023-34453, CVE-2023-34454, CVE-2023-34455
spring-boot-actuator-autoconfigure-2.6.15.jar: CVE-2023-20873
```
```
- BREAKING …
> Roe 2290 suppress issues related to kafka

- pom.xml
https://companieshouse.atlassian.net/browse/ROE-2289
bump api-sdk-java to 4.3.34 which uses Jackson latest version
```
``` …
> bump api-sdk-java to 4.3.34

- suppress.xml
https://companieshouse.atlassian.net/browse/ROE-2289
Suppress disputed CVE that marks all versions as vulnerable.
See https://nvd.nist.gov/vuln/detail/CVE-2023-35116
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of …
> ROE-2289 Suppress disputed vulnerability with Jackson-databind

- Makefile
- suppress.xml
https://companieshouse.atlassian.net/browse/ROE-2317
Configure pipeline jobs to fail if there are security vulnerabilities
```
```
- types other than `fix:` …
> Configure pipeline jobs to fail if there are security vulnerabilities

- pom.xml
Pipelines failures caused by unsupported version of dependency check
Upgrade to parent pom 2.1.6 to use version (10.0.2) of dependency-check
```
```
- types …
> Fix dependency check by Upgrading to latest parent pom

- Makefile
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and …
> remove the routes.raml reference from the makefile

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and …
> fix: remove log_level vars

- pom.xml
https://companieshouse.atlassian.net/browse/ASM-501
Updating Pom to use the latest Sonar version on the pipeline
```
``` …
> ASM-501 Update Pom to use latest Sonar on the pipeline

- README.md
https://companieshouse.atlassian.net/browse/ASM-501
Add whitespace to README to trigger build
```
```
- types other than `fix:` and `feat:` are allowed, for …
> ASM-501 Re-trigger build

- pom.xml
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and …
> upgrading internal dependencies in order to resolve commons-lang issues
